name: CI

on:
  push:
    branches:
      - master
      - ci
      - github-actions
    paths-ignore:
      - guide/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - guide/**

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - ubuntu-18.04
          - ubuntu-20.04
        emacs-version:
          - '25.3'
          - '26.3'
          - '27.2'
        include:
          # Older Emacs binaries for Windows don't have dynamic modules enabled.
          - os: windows-2016
            emacs-version: '27.2'
          - os: windows-2019
            emacs-version: '27.2'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Rust
        run: |
          rustup install stable
          rustc -Vv
          cargo -V

      - uses: actions/checkout@v2

      - name: Build
        run: ./bin/build

      - run: cargo test --all

      - uses: purcell/setup-emacs@v3.0
        if: runner.os != 'Windows'
        with:
          version: ${{ matrix.emacs-version }}

      - uses: jcs090218/setup-emacs-windows@v4
        if: runner.os == 'Windows'
        with:
          version: ${{ matrix.emacs-version }}

      - run: ./bin/test
